### ISSUE TITLE
Caught NaN in diff for kdiff for thread on text8、GoogleNews.

### ISSUE THREAD

**Issue by GuoZi-Fairy** [haozhe-an/DD-GloVe#1]
When I try to run the `demo.sh` on text8, it told me that "Caught NaN in diff for kdiff for thread", and the process died because of "interrupted by signal 10: SIGBUS".

I have try this on different corpus like text8、GoogleNews.
And tried it on different system like windows11、ubuntu 20.02、OS X（Ventura 13.1-apple silicon(M1 Pro) also.

When I check the source code, I find that the `bias_def_value` and `bias_word_value` have never beed update.
Could anyone help me to run the demo?

**Comment by haozhe-an** [comment]
Hi, thanks for reaching out.

It looks like the check did not pass in [this line of the code](https://github.com/haozhe-an/DD-GloVe/blob/99e52936a850b458548db6a5bbeccda837065043/src/glove.c#L250), meaning the variable `dfff` or `fdiff` does not have a valid value for parameter update. When that happens, word vector parameter updates are skipped. Do you have information about which variable has an invalid value? If so, are you able to pinpoint the which operation gives rise to this invalid result (e.g., nan is in word embeddings like `W[b + l1]`? What are the values of `bias_word_value` and `bias_def_value`?)

Not sure if this is the cause of the issue you're experiencing, but I'm curious as to if you have obtained your own copy of dictionary definitions and modified [line 79](https://github.com/haozhe-an/DD-GloVe/blob/99e52936a850b458548db6a5bbeccda837065043/src/glove.c#L79) accordingly to reflect the indices of the two initial seed words.

**Comment by GuoZi-Fairy** [comment]
> Hi, thanks for reaching out.
>
> It looks like the check did not pass in [this line of the code](https://github.com/haozhe-an/DD-GloVe/blob/99e52936a850b458548db6a5bbeccda837065043/src/glove.c#L250), meaning the variable `dfff` or `fdiff` does not have a valid value for parameter update. When that happens, word vector parameter updates are skipped. Do you have information about which variable has an invalid value? If so, are you able to pinpoint the which operation gives rise to this invalid result (e.g., nan is in word embeddings like `W[b + l1]`? What are the values of `bias_word_value` and `bias_def_value`?)
> 
> Not sure if this is the cause of the issue you're experiencing, but I'm curious as to if you have obtained your own copy of dictionary definitions and modified [line 79](https://github.com/haozhe-an/DD-GloVe/blob/99e52936a850b458548db6a5bbeccda837065043/src/glove.c#L79) accordingly to reflect the indices of the two initial seed words.
---
Thanks, it now running perfect.
It is due to that the definition dictionary updating failed by `get_definition.py`.
---
When the definition dictionary not correct, it will make a part of the elements of  `bias_word_value` and `bias_def_value` to `nan`.

**Comment by haozhe-an** [comment]
Awesome! Glad to hear it is working fine now.
